name: Deploy StudyMind Backend

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Deploy on VPS
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.VPS_HOST }}
                  username: ${{ secrets.VPS_USERNAME }}
                  key: ${{ secrets.VPS_SSH_KEY }}
                  script: |
                      cd /home/mdpahlovi/studymind
                      git pull origin main

                      # Load nvm manually
                      export NVM_DIR="$HOME/.nvm"
                      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
                      [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # Optional

                      # Use the correct Node version (optional if default is fine)
                      nvm use 22

                      # Install dependencies, build, and restart app
                      npm install --legacy-peer-deps
                      npm run build
                      pm2 restart studymind || pm2 start dist/index.js --name studymind
