name: Deploy to VPS

on:
    push:
        branches: [main]

jobs:
    deploy:
        runs-on: self-hosted

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Your steps here
              run: echo "Running on self-hosted runner"
